import test from 'node:test';
import assert from 'node:assert/strict';
import { Game } from '../game.js';
import { createApp } from '../server.js';
function setup(size=3){let ms=1_000_000;const game=new Game({time:()=>ms,duration:210000,readyMs:15000,voteMs:15000,resultsMs:15000,random:xs=>xs[0]});const first=game.create('Alex');const members=[first];for(const name of ['Blair','Casey','Drew','Ezra','Finley','Gray','Harper'].slice(0,size-1))members.push(game.join(first.room.code,name));for(const m of members)game.presence(m.token,true);return {g:game,r:first.room,members,advance(n){ms+=n;game.tick();},get ms(){return ms;}};}
function playing(x){x.g.start(x.r,x.members[0].player);assert.equal(x.r.phase,'ready');x.advance(15001);assert.equal(x.r.phase,'playing');}
test('rooms require two players, accept at most eight, check duplicate names, and host controls start',()=>{const x=setup(2);assert.throws(()=>x.g.start(x.r,x.members[1].player),/host/i);assert.throws(()=>x.g.join(x.r.code,'Alex'),/already/i);for(const name of ['Casey','Drew','Ezra','Finley','Gray','Harper'])x.g.join(x.r.code,name);assert.equal(x.r.players.length,8);assert.throws(()=>x.g.join(x.r.code,'Another'),/full/i);playing(x);assert.throws(()=>x.g.join(x.r.code,'Outsider'),/started/i);});
test('two player mode is fully cooperative with no secret traitor',()=>{const x=setup(2);playing(x);assert.equal(x.r.saboteurId,null);assert(x.members.every(m=>x.g.snapshot(x.r,m.player).role==='crew'));assert.throws(()=>x.g.vote(x.r,x.members[0].player,null),/ended/i);});
test('private saboteur identity, gadgets and private mini-games do not leak',()=>{const x=setup(3);playing(x);const sab=x.r.players.find(p=>p.id===x.r.saboteurId),crew=x.r.players.find(p=>p.id!==sab.id);const s=x.g.snapshot(x.r,sab),c=x.g.snapshot(x.r,crew);assert.equal(s.role,'saboteur');assert.equal(c.role,'crew');assert.equal(s.roleGadgets.length,2);assert.equal(c.roleGadgets.length,0);assert.equal(c.roleReveal,undefined);x.g.task(x.r,sab,'memory','cameras');assert.equal(x.g.snapshot(x.r,crew).task,null);assert.equal(x.g.snapshot(x.r,sab).task.type,'memory');});
test('wire, memory, laser puzzles validate on server and score caps at four',()=>{const x=setup(3);playing(x);const p=x.r.players[1];for(const type of ['wires','memory','laser','memory']){const station=type==='laser'?'lasers':'cameras';if(x.r.stationProgress[station]>=x.r.stationTargets){x.r.stationProgress[station]=0;}x.g.task(x.r,p,type,station);const task=p.task;const passed=x.g.submit(x.r,p,task.solution);assert.equal(passed.passed,true);}assert.equal(p.puzzles,4);assert.equal(p.score,60);x.r.stationProgress.cameras=0;x.g.task(x.r,p,'wires','cameras');x.g.submit(x.r,p,p.task.solution);assert.equal(p.score,60);});
test('wrong answer raises alarm and resets task',()=>{const x=setup(3);playing(x);const p=x.r.players[1];x.g.task(x.r,p,'memory','cameras');const r=x.g.submit(x.r,p,[99]);assert.equal(r.passed,false);assert.equal(x.r.alarm,3);assert.equal(p.task,null);});
test('split code actually requires two players to exchange symbols',()=>{const x=setup(3);playing(x);const sender=x.r.players[1],decoder=x.r.players[2];x.g.task(x.r,sender,'split','vault');assert.equal(x.g.snapshot(x.r,sender).task.role,'waiting');x.g.task(x.r,decoder,'split','vault');const task=sender.task;assert.equal(x.g.snapshot(x.r,sender).task.role,'sender');assert.equal(x.g.snapshot(x.r,decoder).task.role,'decoder');assert(!x.g.snapshot(x.r,sender).task.mapping);assert(!x.g.snapshot(x.r,decoder).task.secret);assert.throws(()=>x.g.submit(x.r,decoder,task.solution),/four symbols/i);for(const s of task.secret)x.g.sendSymbol(x.r,sender,s);assert.equal(x.g.submit(x.r,decoder,task.solution).passed,true);assert.equal(x.r.stationProgress.vault,1);assert.equal(sender.score,15);assert.equal(decoder.score,15);});
test('saboteur gadget authorization, two unique charges and recharge',()=>{const x=setup(3);playing(x);const sab=x.r.players.find(p=>p.id===x.r.saboteurId),crew=x.r.players.find(p=>p.id!==sab.id);assert.throws(()=>x.g.sabotage(x.r,crew,'surge','cameras'),/saboteur/i);sab.gadgets=['surge','lockdown'];const first=sab.gadgets[0];x.g.sabotage(x.r,sab,first,'cameras');assert.equal(sab.score,30);assert.throws(()=>x.g.sabotage(x.r,sab,first,'cameras'),/unavailable/i);assert.throws(()=>x.g.sabotage(x.r,sab,sab.gadgets[1],'cameras'),/recharge/i);x.advance(15001);x.g.sabotage(x.r,sab,sab.gadgets[1],'lasers');assert.equal(sab.score,60);});
test('system scramble requires an active puzzle and cancels its target safely',()=>{const x=setup(3);playing(x);const sab=x.r.players.find(p=>p.id===x.r.saboteurId),crew=x.r.players.find(p=>p.id!==sab.id);sab.gadgets=['scramble','surge'];assert.throws(()=>x.g.sabotage(x.r,sab,'scramble','cameras'),/active puzzle/i);x.g.task(x.r,crew,'memory','cameras');assert.equal(crew.task.type,'memory');x.g.sabotage(x.r,sab,'scramble','cameras');assert.equal(crew.task,null);assert.equal(sab.score,30);});
test('alarm repair requires alarm >=10, three taps, cooldown, and caps scoring',()=>{const x=setup(3);playing(x);const p=x.r.players[1];assert.throws(()=>x.g.repair(x.r,p,0),/10%/);x.r.alarm=30;for(const step of x.r.repair.sequence)x.g.repair(x.r,p,step);assert.equal(x.r.alarm,15);assert.equal(p.score,25);assert.throws(()=>x.g.repair(x.r,p,0),/recharging/i);x.advance(25001);for(const step of x.r.repair.sequence)x.g.repair(x.r,p,step);assert.equal(p.score,50);x.advance(25001);x.r.alarm=30;for(const step of x.r.repair.sequence)x.g.repair(x.r,p,step);assert.equal(p.score,50);});
test('two players engaging final breach continuously for eight seconds open vault',()=>{const x=setup(2);playing(x);for(const s of ['cameras','lasers','vault'])x.r.stationProgress[s]=x.r.stationTargets;const a=x.r.players[0],b=x.r.players[1];x.g.arm(x.r,a,true);x.advance(1000);assert.equal(x.r.breachSince,0);x.g.arm(x.r,b,true);x.advance(1000);assert(x.r.breachSince>0);x.advance(8000);assert.equal(x.r.phase,'vote');assert.equal(x.r.crewWon,true);x.advance(15001);assert.equal(x.r.phase,'results');assert.equal(a.score,150);assert.equal(b.score,150);});
test('vote attribution, correct ID, undetected saboteur and three-heist match progression',()=>{const x=setup(3);playing(x);const sab=x.r.players.find(p=>p.id===x.r.saboteurId),others=x.r.players.filter(p=>p!==sab);x.g.finishHeist(x.r,false);x.g.vote(x.r,others[0],sab.id);x.g.vote(x.r,others[1],others[0].id);x.g.vote(x.r,sab,others[0].id);assert.equal(x.r.phase,'results');assert.equal(others[0].score,40);assert.equal(sab.score,190);x.advance(15001);assert.equal(x.r.round,2);x.advance(15001);x.g.finishHeist(x.r,false);x.advance(15001);x.advance(15001);assert.equal(x.r.round,3);x.advance(15001);x.g.finishHeist(x.r,false);x.advance(15001);x.advance(15001);assert.equal(x.r.phase,'finished');});
test('scheduled security sweep and dodge affect alarm fairly',()=>{const x=setup(3);playing(x);x.r.nextEventAt=x.ms+6000;x.r.activeEvent=null;x.g.random=arr=>arr.includes('sweep')?'sweep':arr[0];x.advance(2000);assert.equal(x.r.warning,x.r.nextEventAt);x.advance(4000);assert.equal(x.r.activeEvent.type,'sweep');x.g.react(x.r,x.r.players[0]);x.advance(8001);assert.equal(x.r.alarm,10);});
test('HTTP: two separate browser cookie sessions join one room; SSE private state and valid health',async()=>{const app=createApp();const {port}=await app.listen(0);const base=`http://127.0.0.1:${port}`;try{
 const post=async(path,data,cookie)=>{const res=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json','X-Vault-Action':'1',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(data)});return {body:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0],status:res.status};};
 const a=await post('/api/create',{name:'Alpha'});assert.equal(a.status,200);const b=await post('/api/join',{name:'Beta',code:a.body.state.code});assert.equal(b.status,200);assert.notEqual(a.cookie,b.cookie);
 const meA=await fetch(base+'/api/me',{headers:{Cookie:a.cookie}}).then(r=>r.json());const meB=await fetch(base+'/api/me',{headers:{Cookie:b.cookie}}).then(r=>r.json());assert.equal(meA.state.players.length,2);assert.equal(meB.state.players.length,2);
 const health=await fetch(base+'/health').then(r=>r.json());assert.equal(health.status,'healthy');
 const sse=await fetch(base+'/api/events',{headers:{Cookie:b.cookie}});assert.equal(sse.status,200);assert.match(sse.headers.get('content-type'),/text\/event-stream/);await sse.body.cancel();
 const start=await post('/api/start',{},a.cookie);assert.equal(start.status,200);assert.equal(start.body.state.phase,'ready');const bad=await post('/api/start',{},b.cookie);assert.equal(bad.status,400);
}finally{await app.close();}});
